name: Process PS Module
on: push

jobs:
  build:

    name: Build module
    runs-on: windows-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.8
        with:
          versionSpec: '5.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.8
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Display SemVer
        run: |
          echo "SemVer: $GITVERSION_SEMVER"

      - name: Display MajorMinorPatch
        run: |
          echo "MajorMinorPatch: $GITVERSION_MAJORMINORPATCH"

      - name: Execute Build
        run: tools/build.ps1 -Task BuildWithTests
        shell: pwsh

      - name: Upload Release artifact
        uses: actions/upload-artifact@v2
        with:
          name: Release
          path: ${{ github.workspace }}/Release

      - name: Upload Tools artifact
        uses: actions/upload-artifact@v2
        with:
          name: Tools
          path: ${{ github.workspace }}/tools


  test_release:

    name: Test Release module
    if: ${{ github.ref == 'refs/heads/feature/create-ci' }}
    runs-on: windows-latest
    needs: build
    steps:

      - name: Download artifact
        uses: actions/download-artifact@v2

      - name: Display structure of downloaded files
        run: Get-Childitem -Recurse
        shell: pwsh

      - name: Publish Module to Test PowerShell gallery
        run: .\Tools\Publish-PSModule.ps1 -ApiKey ${{ secrests.PSTestGalleryApiKey }} -Path ".\Release\actions-test" -CheckForExistingVersion -PreRelease -Verbose
        shell: pwsh